"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { createClient, type SupabaseClient, type User } from "@supabase/supabase-js";

type Quadrant = "do" | "plan" | "delegate" | "drop";
type Task = { id:number; text:string; done:boolean; date:string; quadrant:Quadrant };
type Goal = { id:number; title:string; done:boolean; kind:"week"|"today" };
type EnergyKey = "physical"|"emotional"|"mental"|"will";
type EnergyGoal = { id:number; dimension:EnergyKey; title:string; target:number; completed:number };
type Thought = { id:number; createdAt:string; text:string };
type Review = { flash:string; challenge:string; nextGoal:string };
type AppState = { tasks:Task[]; goals:Goal[]; energyGoals:EnergyGoal[]; thoughts:Thought[]; reviews:Record<string,Review> };
type CloudConfig = { url:string; anonKey:string };

const iso=(d:Date)=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const todayIso=()=>iso(new Date());
function weekRange(base=new Date()){
  const d=new Date(base); d.setHours(12,0,0,0); const offset=(d.getDay()+1)%7;
  const start=new Date(d); start.setDate(d.getDate()-offset);
  const end=new Date(start); end.setDate(start.getDate()+6);
  const fmt=(x:Date)=>`${x.getMonth()+1}月${x.getDate()}日`;
  return {start:iso(start),end:iso(end),label:`${fmt(start)}—${fmt(end)}`};
}
const dims:{key:EnergyKey;name:string;hint:string;icon:string}[]=[
  {key:"physical",name:"物理能量",hint:"睡眠 · 饮食 · 活动",icon:"◒"},{key:"emotional",name:"情感能量",hint:"关系 · 感受 · 联结",icon:"♡"},
  {key:"mental",name:"思维能量",hint:"专注 · 清晰 · 创造",icon:"◇"},{key:"will",name:"意志能量",hint:"行动 · 决断 · 坚持",icon:"△"}
];
const starterTasks:Task[]=[
  {id:1,text:"投递 1 个真正心动的岗位",done:false,date:todayIso(),quadrant:"do"},
  {id:2,text:"完成 PawMory 本周内容选题",done:false,date:todayIso(),quadrant:"plan"},
  {id:3,text:"散步 30 分钟，让身体透透气",done:true,date:todayIso(),quadrant:"plan"},
];
const starterGoals:Goal[]=[
  {id:11,title:"完成本周重点求职计划",done:false,kind:"week"},{id:12,title:"完成 PawMory 内容发布",done:false,kind:"week"},
  {id:13,title:"只抓住今天最重要的三件事",done:false,kind:"today"}
];
const starterEnergy:EnergyGoal[]=[
  {id:21,dimension:"physical",title:"游泳",target:2,completed:0},{id:22,dimension:"physical",title:"23:30 前睡觉",target:5,completed:0},
  {id:23,dimension:"emotional",title:"和重要的人好好聊天",target:2,completed:0},{id:24,dimension:"mental",title:"专注阅读 30 分钟",target:4,completed:0},
  {id:25,dimension:"will",title:"完成今日三件事",target:5,completed:0}
];
const emptyReview:Review={flash:"",challenge:"",nextGoal:""};
const normalizeReview=(review:any):Review=>({
  flash:review?.flash||[review?.proud,review?.gratitude,review?.lesson].filter(Boolean).join("\n"),
  challenge:review?.challenge||[review?.unfinished,review?.energy,review?.adjustment].filter(Boolean).join("\n"),
  nextGoal:review?.nextGoal||review?.next||""
});
const nav=[["overview","总览","⌂"],["today","今日计划","✓"],["goals","周计划","◎"],["energy","能量空间","≈"],["review","周复盘","↻"],["thoughts","碎碎念","✦"],["cloud","云端同步","☁"]];
const quadrants:{key:Quadrant;title:string;sub:string;accent:string}[]=[
  {key:"do",title:"重要且紧急",sub:"立即去做",accent:"coral"},{key:"plan",title:"重要不紧急",sub:"安排时间",accent:"blue"},
  {key:"delegate",title:"紧急不重要",sub:"简化或协作",accent:"amber"},{key:"drop",title:"不紧急不重要",sub:"减少或放下",accent:"gray"}
];

export default function Home(){
  const [view,setView]=useState("overview"); const [tasks,setTasks]=useState<Task[]>(starterTasks); const [goals,setGoals]=useState<Goal[]>(starterGoals);
  const [energyGoals,setEnergyGoals]=useState<EnergyGoal[]>(starterEnergy); const [thoughts,setThoughts]=useState<Thought[]>([]); const [reviews,setReviews]=useState<Record<string,Review>>({});
  const [loaded,setLoaded]=useState(false); const [taskText,setTaskText]=useState(""); const [taskDate,setTaskDate]=useState(todayIso()); const [taskQuadrant,setTaskQuadrant]=useState<Quadrant>("do");
  const [goalText,setGoalText]=useState(""); const [goalKind,setGoalKind]=useState<"week"|"today">("week"); const [thoughtText,setThoughtText]=useState(""); const [editingThought,setEditingThought]=useState<number|null>(null);
  const [newEnergy,setNewEnergy]=useState<Record<EnergyKey,string>>({physical:"",emotional:"",mental:"",will:""});
  const [cloudConfig,setCloudConfig]=useState<CloudConfig>({url:"",anonKey:""}); const [cloudDraft,setCloudDraft]=useState<CloudConfig>({url:"",anonKey:""});
  const [supabase,setSupabase]=useState<SupabaseClient|null>(null); const [user,setUser]=useState<User|null>(null); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  const [cloudStatus,setCloudStatus]=useState("尚未连接 Supabase"); const cloudReady=useRef(false); const saveTimer=useRef<number|null>(null);
  const [seconds,setSeconds]=useState(1500); const [running,setRunning]=useState(false); const [focusMode,setFocusMode]=useState<"focus"|"break">("focus");
  const week=useMemo(()=>weekRange(),[]); const review=reviews[week.start]||emptyReview;

  useEffect(()=>{const raw=localStorage.getItem("my-life-v2")||localStorage.getItem("my-life-v1");if(raw)try{const d=JSON.parse(raw);if(d.tasks)setTasks(d.tasks.map((t:Task)=>({...t,date:t.date||todayIso(),quadrant:t.quadrant||"do"})));if(d.goals)setGoals(d.goals.map((g:any)=>({id:g.id,title:g.title,done:g.done??g.progress===100,kind:g.kind||"week"})));if(d.energyGoals)setEnergyGoals(d.energyGoals);if(d.thoughts)setThoughts(d.thoughts);else if(d.growth)setThoughts(d.growth.map((g:any)=>({id:g.id,createdAt:g.date,text:[g.title,g.note].filter(Boolean).join("\n")})));if(d.reviews)setReviews(Object.fromEntries(Object.entries(d.reviews).map(([key,value])=>[key,normalizeReview(value)])));else if(d.review)setReviews({[week.start]:normalizeReview({proud:d.review.win||"",lesson:d.review.learn||"",next:d.review.next||"",unfinished:d.review.difficult||""})})}catch{}setLoaded(true)},[week.start]);
  useEffect(()=>{if(loaded)localStorage.setItem("my-life-v2",JSON.stringify({tasks,goals,energyGoals,thoughts,reviews}))},[tasks,goals,energyGoals,thoughts,reviews,loaded]);
  useEffect(()=>{const raw=localStorage.getItem("my-life-supabase");if(raw)try{const config=JSON.parse(raw) as CloudConfig;if(config.url&&config.anonKey){setCloudConfig(config);setCloudDraft(config)}}catch{}},[]);
  useEffect(()=>{if(!cloudConfig.url||!cloudConfig.anonKey){setSupabase(null);return}try{const client=createClient(cloudConfig.url,cloudConfig.anonKey);setSupabase(client);setCloudStatus("正在连接云端…");client.auth.getUser().then(({data})=>setUser(data.user));const {data:{subscription}}=client.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>subscription.unsubscribe()}catch{setCloudStatus("Supabase 配置无效，请检查后重试")}},[cloudConfig]);
  useEffect(()=>{if(!supabase||!user||!loaded)return;cloudReady.current=false;setCloudStatus("正在读取云端数据…");supabase.from("my_life_state").select("data").eq("user_id",user.id).maybeSingle().then(({data,error})=>{if(error){setCloudStatus(`读取失败：${error.message}`);return}if(data?.data){const d=data.data as AppState;setTasks(d.tasks||[]);setGoals(d.goals||[]);setEnergyGoals(d.energyGoals||[]);setThoughts(d.thoughts||[]);setReviews(d.reviews||{});setCloudStatus("云端数据已同步")}else{setCloudStatus("云端尚无数据，当前记录将自动上传")}cloudReady.current=true})},[supabase,user,loaded]);
  useEffect(()=>{if(!supabase||!user||!loaded||!cloudReady.current)return;if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(async()=>{setCloudStatus("正在保存…");const state:AppState={tasks,goals,energyGoals,thoughts,reviews};const {error}=await supabase.from("my_life_state").upsert({user_id:user.id,data:state,updated_at:new Date().toISOString()},{onConflict:"user_id"});setCloudStatus(error?`保存失败：${error.message}`:"已保存至 Supabase")},700);return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current)}},[tasks,goals,energyGoals,thoughts,reviews,supabase,user,loaded]);
  useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(timer)},[running]);

  const weekTasks=tasks.filter(t=>t.date>=week.start&&t.date<=week.end); const todayTasks=tasks.filter(t=>t.date===todayIso());
  const weekGoals=goals.filter(g=>g.kind==="week"), todayGoals=goals.filter(g=>g.kind==="today");
  const pct=(items:{done:boolean}[])=>items.length?Math.round(items.filter(x=>x.done).length/items.length*100):0;
  const energy=Object.fromEntries(dims.map(d=>{const gs=energyGoals.filter(g=>g.dimension===d.key);const total=gs.reduce((a,g)=>a+g.target,0);const complete=gs.reduce((a,g)=>a+Math.min(g.completed,g.target),0);return[d.key,total?Math.round(complete/total*100):0]})) as Record<EnergyKey,number>;
  const avgEnergy=Math.round(Object.values(energy).reduce((a,b)=>a+b,0)/4); const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  const date=new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric",weekday:"long"}).format(new Date());
  const toggleTask=(id:number)=>setTasks(v=>v.map(t=>t.id===id?{...t,done:!t.done}:t));
  const addTask=()=>{if(!taskText.trim())return;setTasks(v=>[...v,{id:Date.now(),text:taskText.trim(),done:false,date:taskDate,quadrant:taskQuadrant}]);setTaskText("")};
  const addGoal=()=>{if(!goalText.trim())return;setGoals(v=>[...v,{id:Date.now(),title:goalText.trim(),done:false,kind:goalKind}]);setGoalText("")};
  const updateReview=(k:keyof Review,v:string)=>setReviews(x=>({...x,[week.start]:{...review,[k]:v}}));
  const saveThought=()=>{if(!thoughtText.trim())return;if(editingThought)setThoughts(v=>v.map(x=>x.id===editingThought?{...x,text:thoughtText.trim()}:x));else setThoughts(v=>[{id:Date.now(),createdAt:new Date().toISOString(),text:thoughtText.trim()},...v]);setThoughtText("");setEditingThought(null)};
  const downloadTxt=(content:string,filename:string)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\uFEFF",content],{type:"text/plain;charset=utf-8"}));a.download=filename;a.click();URL.revokeObjectURL(a.href)};
  const exportReview=()=>{const lines=[`MY LIFE · 周复盘`,`周期：${week.label}`,`本周目标：${goals.filter(g=>g.kind==="week"&&g.done).length}/${weekGoals.length}`,`本周任务：${weekTasks.filter(t=>t.done).length}/${weekTasks.length}`,`综合能量：${avgEnergy}%`,``,`【本周计划与目标】`,...weekGoals.map(g=>`${g.done?"✓":"○"} ${g.title}`),``,`【本周任务完成】`,...weekTasks.map(t=>`${t.done?"✓":"○"} ${t.date} ${t.text}`),...Object.entries({本周闪光:review.flash,本周挑战:review.challenge,下周目标:review.nextGoal}).flatMap(([k,v])=>["",`【${k}】`,v||"暂未填写"])];downloadTxt(lines.join("\n"),`My-Life-周报-${week.start}-${week.end}.txt`)};
  const exportThoughts=()=>{const sorted=[...thoughts].sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime());const lines=["MY LIFE · 全部碎碎念",`导出时间：${new Date().toLocaleString("zh-CN")}`,`共 ${sorted.length} 条记录`,"",...sorted.flatMap((t,index)=>[`【${index+1}】${new Date(t.createdAt).toLocaleString("zh-CN")}`,t.text,""])];downloadTxt(lines.join("\n"),`My-Life-全部碎碎念-${todayIso()}.txt`)};
  const setTimer=(m:"focus"|"break")=>{setRunning(false);setFocusMode(m);setSeconds(m==="focus"?1500:300)};
  const saveCloudConfig=()=>{const config={url:cloudDraft.url.trim().replace(/\/$/,""),anonKey:cloudDraft.anonKey.trim()};localStorage.setItem("my-life-supabase",JSON.stringify(config));setCloudConfig(config);setCloudStatus("配置已保存，正在连接…")};
  const signIn=async()=>{if(!supabase)return;setCloudStatus("正在登录…");const {error}=await supabase.auth.signInWithPassword({email,password});setCloudStatus(error?`登录失败：${error.message}`:"登录成功，正在同步…")};
  const signUp=async()=>{if(!supabase)return;setCloudStatus("正在创建账号…");const {error}=await supabase.auth.signUp({email,password});setCloudStatus(error?`注册失败：${error.message}`:"注册成功。若开启了邮箱验证，请先查收验证邮件。")} ;

  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">M</span><div><strong>My Life！</strong><small>我的人生工作台</small></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i>{label}</button>)}</nav><div className="sidebar-tide"><span>本周能量</span><strong>{avgEnergy}%</strong><div><b style={{width:`${avgEnergy}%`}}/></div><small>{week.label}</small></div><p className="save-note"><span>●</span> 已自动保存</p></aside>
  <section className="content"><header><div><p className="eyebrow">{date} · 本周 {week.label}</p><h1>{view==="overview"?"今天，也向自己的方向靠近一点":nav.find(n=>n[0]===view)?.[1]}</h1></div><button className={`avatar ${user?"online":""}`} title={user?"云端已登录":"设置云端同步"} onClick={()=>setView("cloud")}>{user?"✓":"ME"}</button></header>
  {view==="overview"&&<><section className="week-banner"><div><small>THIS WEEK · 周六至周五</small><h2>{week.label}</h2><p>让一周有边界，也给每一次重新开始留出位置。</p></div><div className="ring" style={{"--p":`${pct(weekGoals)}%`} as React.CSSProperties}><strong>{pct(weekGoals)}%</strong><span>周目标</span></div><div className="ring light" style={{"--p":`${pct(todayGoals)}%`} as React.CSSProperties}><strong>{pct(todayGoals)}%</strong><span>今日目标</span></div></section><section className="overview-focus"><article className="panel"><PanelTitle title="本周与今天" sub="目标完成情况一眼看清" action="查看周计划" onClick={()=>setView("goals")}/><GoalSummary title="本周目标" goals={weekGoals} onToggle={id=>setGoals(v=>v.map(g=>g.id===id?{...g,done:!g.done}:g))}/><GoalSummary title="今天目标" goals={todayGoals} onToggle={id=>setGoals(v=>v.map(g=>g.id===id?{...g,done:!g.done}:g))}/></article><Pomodoro time={time} running={running} focusMode={focusMode} seconds={seconds} setTimer={setTimer} setRunning={setRunning}/></section><section className="dashboard-grid"><article className="panel"><PanelTitle title="今日三件事" sub={`${todayTasks.filter(t=>t.done).length}/${todayTasks.length} 已完成`} action="查看计划" onClick={()=>setView("today")}/><TaskList tasks={todayTasks.slice(0,3)} toggle={toggleTask}/></article><article className="panel"><PanelTitle title="能量罗盘" sub="由本周重复目标的完成度生成" action="查看目标" onClick={()=>setView("energy")}/><EnergyBars energy={energy}/></article></section></>}
  {view==="today"&&<><section className="panel task-builder"><PanelTitle title="添加每日详细任务" sub="选择日期，再放入合适的优先级象限"/><div className="add-grid"><input value={taskText} onChange={e=>setTaskText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addTask()} placeholder="写下具体、可以完成的任务…"/><input aria-label="任务日期" type="date" value={taskDate} onChange={e=>setTaskDate(e.target.value)}/><select value={taskQuadrant} onChange={e=>setTaskQuadrant(e.target.value as Quadrant)}>{quadrants.map(q=><option key={q.key} value={q.key}>{q.title}</option>)}</select><button className="primary" onClick={addTask}>＋ 添加任务</button></div></section><section className="quadrant-grid">{quadrants.map(q=><article className={`panel quadrant ${q.accent}`} key={q.key}><div className="quadrant-head"><div><h2>{q.title}</h2><p>{q.sub}</p></div><strong>{weekTasks.filter(t=>t.quadrant===q.key&&t.done).length}/{weekTasks.filter(t=>t.quadrant===q.key).length}</strong></div><TaskList tasks={weekTasks.filter(t=>t.quadrant===q.key).sort((a,b)=>a.date.localeCompare(b.date))} toggle={toggleTask} showDate/></article>)}</section></>}
  {view==="goals"&&<><section className="panel task-builder"><PanelTitle title="本周计划" sub={`${week.label} · 周六开始，周五结束`}/><div className="add-grid"><input value={taskText} onChange={e=>setTaskText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addTask()} placeholder="写下本周要完成的具体任务…"/><input aria-label="计划日期" type="date" min={week.start} max={week.end} value={taskDate} onChange={e=>setTaskDate(e.target.value)}/><select value={taskQuadrant} onChange={e=>setTaskQuadrant(e.target.value as Quadrant)}>{quadrants.map(q=><option key={q.key} value={q.key}>{q.title}</option>)}</select><button className="primary" onClick={addTask}>＋ 加入周计划</button></div></section><section className="week-plan-summary"><Stat label="本周任务" value={`${weekTasks.length}`} note={`${weekTasks.filter(t=>t.done).length} 项已完成`}/><Stat label="完成进度" value={`${pct(weekTasks)}%`} note={`${week.start} 至 ${week.end}`}/><Stat label="今日安排" value={`${todayTasks.length}`} note={`${todayTasks.filter(t=>t.done).length} 项已完成`}/></section><section className="quadrant-grid">{quadrants.map(q=><article className={`panel quadrant ${q.accent}`} key={q.key}><div className="quadrant-head"><div><h2>{q.title}</h2><p>{q.sub}</p></div><strong>{weekTasks.filter(t=>t.quadrant===q.key&&t.done).length}/{weekTasks.filter(t=>t.quadrant===q.key).length}</strong></div><TaskList tasks={weekTasks.filter(t=>t.quadrant===q.key).sort((a,b)=>a.date.localeCompare(b.date))} toggle={toggleTask} showDate/></article>)}</section></>}
  {view==="energy"&&<><section className="energy-intro"><div><small>ENERGY COMPASS</small><h2>能量不是主观评分，<br/>而是你照顾自己的证据。</h2><p>每完成一次重复目标，能量水位就会上升。目标可以随时新增，也可以调整本周次数。</p></div><div className="energy-orb"><div style={{height:`${avgEnergy}%`}}/><strong>{avgEnergy}%</strong><small>综合能量</small></div></section><section className="energy-goal-grid">{dims.map(d=>{const gs=energyGoals.filter(g=>g.dimension===d.key);return <article className="panel energy-goal" key={d.key}><div className="energy-heading"><i>{d.icon}</i><div><h2>{d.name}</h2><p>{d.hint}</p></div><strong>{energy[d.key]}%</strong></div>{gs.map(g=><div className="repeat-goal" key={g.id}><span><b>{g.title}</b><small>本周 {g.completed}/{g.target} 次</small></span><button disabled={g.completed===0} onClick={()=>setEnergyGoals(v=>v.map(x=>x.id===g.id?{...x,completed:Math.max(0,x.completed-1)}:x))}>−</button><button onClick={()=>setEnergyGoals(v=>v.map(x=>x.id===g.id?{...x,completed:Math.min(x.target,x.completed+1)}:x))}>＋</button><input aria-label="目标次数" type="number" min="1" max="30" value={g.target} onChange={e=>setEnergyGoals(v=>v.map(x=>x.id===g.id?{...x,target:Math.max(1,+e.target.value),completed:Math.min(x.completed,Math.max(1,+e.target.value))}:x))}/><button className="trash" onClick={()=>setEnergyGoals(v=>v.filter(x=>x.id!==g.id))}>×</button></div>)}<div className="mini-add"><input value={newEnergy[d.key]} onChange={e=>setNewEnergy({...newEnergy,[d.key]:e.target.value})} placeholder="新增重复目标…"/><button onClick={()=>{const title=newEnergy[d.key].trim();if(!title)return;setEnergyGoals(v=>[...v,{id:Date.now(),dimension:d.key,title,target:1,completed:0}]);setNewEnergy({...newEnergy,[d.key]:""})}}>添加</button></div></article>})}</section></>}
  {view==="review"&&<section className="panel review"><PanelTitle title="这一周，我航行得怎么样？" sub={`${week.label} · 计划、行动、能量与感受`} action="导出本周周报" onClick={exportReview}/><div className="review-summary"><Stat label="周目标" value={`${pct(weekGoals)}%`} note={`${weekGoals.filter(g=>g.done).length}/${weekGoals.length} 已完成`}/><Stat label="周任务" value={`${pct(weekTasks)}%`} note={`${weekTasks.filter(t=>t.done).length}/${weekTasks.length} 已完成`}/><Stat label="综合能量" value={`${avgEnergy}%`} note="由重复目标生成"/></div><div className="review-plan"><GoalSummary title="本周原定目标" goals={weekGoals} onToggle={id=>setGoals(v=>v.map(g=>g.id===id?{...g,done:!g.done}:g))}/><div><h3>本周任务概况</h3><p>共安排 {weekTasks.length} 项，完成 {weekTasks.filter(t=>t.done).length} 项；其中重要且紧急 {weekTasks.filter(t=>t.quadrant==="do").length} 项。</p><div className="progress"><b style={{width:`${pct(weekTasks)}%`}}/></div></div></div><div className="review-grid">{([['flash','本周闪光','这一周有哪些值得珍藏、值得为自己鼓掌的时刻？'],['challenge','本周挑战','遇到了什么困难？它带来了哪些提醒？'],['nextGoal','下周目标','下一周最重要、最想完成的目标是什么？']] as const).map(([k,t,p])=><label key={k} className={k==="nextGoal"?"wide-field":""}><b>{t}</b><textarea value={review[k]} onChange={e=>updateReview(k,e.target.value)} placeholder={p}/></label>)}</div></section>}
  {view==="thoughts"&&<section className="thought-layout"><article className="panel thought-compose"><PanelTitle title={editingThought?"修改这条碎碎念":"此刻，想说点什么？"} sub="无需完整，也不用有结论"/><textarea value={thoughtText} onChange={e=>setThoughtText(e.target.value)} placeholder="一闪而过的念头、今天的小情绪、突然想记住的事情……"/><div><button className="primary" onClick={saveThought}>{editingThought?"保存修改":"记下此刻"}</button>{editingThought&&<button className="ghost" onClick={()=>{setEditingThought(null);setThoughtText("")}}>取消</button>}</div></article><article className="panel"><PanelTitle title="我的碎碎念" sub={`已记录 ${thoughts.length} 个生活切片`} action="导出全部 TXT" onClick={exportThoughts}/><div className="thought-list">{thoughts.length===0?<div className="empty"><span>≈</span><h3>第一句话，等你落下来</h3><p>一天可以写很多次。这里不要求成长，只负责诚实。</p></div>:thoughts.map(t=><article className="thought" key={t.id}><div><time>{new Date(t.createdAt).toLocaleString("zh-CN",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time><p>{t.text}</p></div><aside><button onClick={()=>{setEditingThought(t.id);setThoughtText(t.text)}}>修改</button><button className="danger" onClick={()=>{if(confirm("确定删除这条碎碎念吗？"))setThoughts(v=>v.filter(x=>x.id!==t.id))}}>删除</button></aside></article>)}</div></article></section>}
  {view==="cloud"&&<section className="cloud-layout"><article className="panel cloud-card"><PanelTitle title="Supabase 云端同步" sub="登录后，电脑和手机会读取同一份 My Life 数据"/><div className={`cloud-status ${user?"ok":""}`}><span>{user?"●":"○"}</span><div><b>{user?`已登录：${user.email}`:"尚未登录"}</b><small>{cloudStatus}</small></div></div>{!supabase&&<><label>Project URL<input value={cloudDraft.url} onChange={e=>setCloudDraft({...cloudDraft,url:e.target.value})} placeholder="https://xxxx.supabase.co"/></label><label>Anon public key<input type="password" value={cloudDraft.anonKey} onChange={e=>setCloudDraft({...cloudDraft,anonKey:e.target.value})} placeholder="Supabase anon key"/></label><button className="primary" onClick={saveCloudConfig}>保存 Supabase 配置</button></>}{supabase&&!user&&<><label>邮箱<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="至少 6 位密码"/></label><div className="cloud-actions"><button className="primary" onClick={signIn}>登录并同步</button><button className="ghost" onClick={signUp}>创建账号</button><button className="text-button" onClick={()=>{localStorage.removeItem("my-life-supabase");setCloudConfig({url:"",anonKey:""});setCloudDraft({url:"",anonKey:""})}}>更换项目</button></div></>}{supabase&&user&&<div className="cloud-actions"><button className="ghost" onClick={()=>supabase.auth.signOut()}>退出登录</button><button className="text-button" onClick={()=>{localStorage.removeItem("my-life-supabase");setCloudConfig({url:"",anonKey:""});setCloudDraft({url:"",anonKey:""})}}>更换 Supabase 项目</button></div>}</article><article className="panel cloud-guide"><small>ONE CLOUD · ALL DEVICES</small><h2>你的记录，由你自己的数据库保管。</h2><p>当前浏览器中的旧任务、能量目标、周复盘和碎碎念会在首次登录后自动上传；以后每次修改都会自动保存。</p><ol><li>在 Supabase 执行项目包中的 <b>supabase-schema.sql</b></li><li>填入 Project URL 和 anon public key</li><li>使用邮箱注册或登录</li></ol><p className="privacy-note">Anon key 可以用于网页前端；数据访问由数据库的 RLS 规则限制为仅本人。</p></article></section>}
  </section></main>
}

function PanelTitle({title,sub,action,onClick}:{title:string;sub:string;action?:string;onClick?:()=>void}){return <div className="panel-title"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function TaskList({tasks,toggle,showDate=false}:{tasks:Task[];toggle:(id:number)=>void;showDate?:boolean}){return <div className="task-list">{tasks.length===0?<p className="soft-empty">这里还没有任务</p>:tasks.map(t=><label key={t.id} className={t.done?"done":""}><button aria-label="切换完成状态" onClick={()=>toggle(t.id)}>{t.done?"✓":""}</button><span>{t.text}</span>{showDate&&<small>{t.date.slice(5).replace("-","/")}</small>}</label>)}</div>}
function GoalSummary({title,goals,onToggle}:{title:string;goals:Goal[];onToggle:(id:number)=>void}){return <div className="goal-summary"><h3>{title}<span>{goals.filter(g=>g.done).length}/{goals.length}</span></h3>{goals.length===0?<p className="soft-empty">还没有设定目标</p>:goals.map(g=><label key={g.id} className={g.done?"done":""}><button onClick={()=>onToggle(g.id)}>{g.done?"✓":""}</button><span>{g.title}</span></label>)}</div>}
function GoalManager({title,goals,setGoals}:{title:string;goals:Goal[];setGoals:React.Dispatch<React.SetStateAction<Goal[]>>}){return <article><h2>{title}</h2>{goals.map(g=><div className={`managed-goal ${g.done?"done":""}`} key={g.id}><button onClick={()=>setGoals(v=>v.map(x=>x.id===g.id?{...x,done:!x.done}:x))}>{g.done?"✓":""}</button><span>{g.title}</span><button className="trash" onClick={()=>setGoals(v=>v.filter(x=>x.id!==g.id))}>×</button></div>)}</article>}
function EnergyBars({energy}:{energy:Record<EnergyKey,number>}){return <div className="energy-bars">{dims.map(d=><div key={d.key}><span>{d.name.slice(0,2)}</span><i><b style={{height:`${energy[d.key]}%`}}/></i><strong>{energy[d.key]}</strong></div>)}</div>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <article className="stat"><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Pomodoro({time,running,focusMode,seconds,setTimer,setRunning}:{time:string;running:boolean;focusMode:string;seconds:number;setTimer:(m:"focus"|"break")=>void;setRunning:(v:boolean)=>void}){const total=focusMode==="focus"?1500:300;return <article className="ocean-card timer"><div className="timer-tabs"><button className={focusMode==="focus"?"on":""} onClick={()=>setTimer("focus")}>专注 25</button><button className={focusMode==="break"?"on":""} onClick={()=>setTimer("break")}>休息 5</button></div><div className="clock" style={{"--progress":`${(1-seconds/total)*360}deg`} as React.CSSProperties}><div><strong>{time}</strong><small>{focusMode==="focus"?"深潜专注":"浮上海面"}</small></div></div><button className="start" onClick={()=>setRunning(!running)}>{running?"暂停片刻":"开始专注"}</button></article>}
